---
title: "Titanic - Machine Learning from Disaster"
author: Hong (H@g.com)
date: "`r format(Sys.Date())`" 
output:
  html_document:
    fig_height: 6
    fig_width: 10
    highlight: textmate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes    
  pdf_document:
    extra_dependencies: ["kotex"]
    fig_height: 6
    fig_width: 10
    toc: yes
    toc_depth: 3
  word_document:
    fig_height: 6
    fig_width: 10
    toc: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=T, message=F, warning=F, fig.height = 8, cache=T, dpi = 300, dev = "png")
library(tidyverse)
library(tidymodels)
library(mice)
```

> `Kaggle`의 대표적인 `Competition` 중 하나인 `Titanic 생존자 예측`에 관한 내용을 다루고 있습니다. 처음 `Kaggle`에 도전하시는 분들이 참고하실만한 자료가 되었으면 합니다.

# 데이터 불러오기

`titanic competition`에서는 `Model`을 생성하는데 사용하는 `train` data와 실제 예측(추정)에 사용하는 `test` data가 분리되어 있습니다. 여기서는 저 2개 data들을 불러와서 하나로 묶을 것 입니다. 따로 분리되어 있는 데이터들을 하나로 묶는 이유는 모델링에 사용되는 입력변수들을 Feature engineering, Pre-processing 할 때 동일하게 작업하기 위해서 입니다.

```{r}
df_titanic <-
  read_csv("data/titanic_train.csv") %>% 
  rename_all(tolower) 
df_titanic
df_titanic_competition <- 
  read_csv("data/titanic_test.csv") %>% 
  rename_all(tolower) 
df_titanic_competition
```

